### ISSUE TITLE
Functional: Data needed from external sources

### ISSUE THREAD

**Issue by pkoers** [pkoers/blue-water#4]
The following data is needed from external sources (source: Shall I short this stock checklist):

- [x] Majority Holders (Yahoo! Finance)
- [x] Get Finnhub API #5
- [x] Market Cap #6 
- [x] (most actual) Stock Price #7 
- [x] Country HQ #6 
- [ ] Cash Position (from Dilution Tracker) #8 
- [ ] Adding Company MCV #10
